// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSJ0jhr4MLWQHxHGBnVW2rcl_m6UDyYTs',
    appId: '1:70611456559:android:a10a4ba7081e0ac973acda',
    messagingSenderId: '70611456559',
    projectId: 'qnews-5739b',
    storageBucket: 'qnews-5739b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPEyASA_HNaS6Ial9AdDtuxuSGBLw6ugI',
    appId: '1:70611456559:ios:cc923f0eb17319f573acda',
    messagingSenderId: '70611456559',
    projectId: 'qnews-5739b',
    storageBucket: 'qnews-5739b.appspot.com',
    androidClientId: '70611456559-f73gd6l8nvkj8uk5lth16ujroihooao9.apps.googleusercontent.com',
    iosClientId: '70611456559-ou5naqirulpo80jf3ovpmk82gjvag2fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );
}
